// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authoritative committed Agent Management phase projected by Cutex for live presentation.
 */
export type AgentManagementPhase = "prepared" | "privateCwdReady" | "nativeBootstrapPending" | "nativeSessionCaptured" | "adopted" | "configured" | "online" | "ready" | "messagePending" | "messageQueued" | "predecessorClosing" | "predecessorClosed" | "authorityTransferPending" | "authorityTransferred" | "successorReady" | "complete" | "noWrite" | "ownerActionRequired" | "failure";
