// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional presentation-only attributes for a Cutex participant.
 *
 * Every field is an authenticated hint supplied by Cutex. Consumers must not infer missing
 * values from Agent paths, runtime IDs, message bodies, groups, working directories, or prose.
 */
export type CutexParticipantPresentation = { displayName?: string, cutexSessionId?: string, profile?: string, model?: string, reasoning?: string, role?: string, runtimeBackend?: string, };
