// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CutexUiActivityDelivery } from "./CutexUiActivityDelivery";
import type { ThreadItem } from "./ThreadItem";

/**
 * A strictly UI-only Cutex activity accepted with its authoritative delivery envelope.
 */
export type CutexUiActivityNotification = { threadId: string, delivery: CutexUiActivityDelivery, item: ThreadItem, };
