// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CutexUiActivityCheckpoint } from "./CutexUiActivityCheckpoint";
import type { CutexUiActivityDeliveryClass } from "./CutexUiActivityDeliveryClass";
import type { CutexUiActivityDeliverySchema } from "./CutexUiActivityDeliverySchema";

/**
 * Required transport facts for one producer-projected Cutex UI activity.
 */
export type CutexUiActivityDelivery = { schema: CutexUiActivityDeliverySchema, class: CutexUiActivityDeliveryClass, recovered: boolean, batchId: string, batchIndex: number, batchSize: number, sourceCheckpoint: CutexUiActivityCheckpoint, batchCheckpoint: CutexUiActivityCheckpoint, };
