// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalInputHoldReason } from "./ExternalInputHoldReason";
import type { ExternalInputProcessingState } from "./ExternalInputProcessingState";

export type ExternalInputProcessingStatus = { state: ExternalInputProcessingState, attemptId: string | null, reason: ExternalInputHoldReason | null, };
