// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalInputHoldReason = "canonical_size_policy" | "plan_mode" | "interrupted" | "request_uncertain" | "no_output" | "context_missing";
