// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalInputDeliveryState } from "./ExternalInputDeliveryState";
import type { ExternalInputProcessingStatus } from "./ExternalInputProcessingStatus";
import type { ExternalInputReceipt } from "./ExternalInputReceipt";

export type ExternalInputStatus = { messageId: string, semanticSha256: string, deliveryState: ExternalInputDeliveryState, receipt: ExternalInputReceipt | null, processing: ExternalInputProcessingStatus, };
