// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalInputReceipt = { schema: string, receiptId: string, ownerId: string, threadId: string, messageId: string, semanticSha256: string, responseItemId: string, turnId: string, ordinal: bigint, };
