// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalInputDelivery } from "./ExternalInputDelivery";
import type { ExternalInputSource } from "./ExternalInputSource";

export type ExternalInputMessage = { id: string, source: ExternalInputSource, type: string, delivery: ExternalInputDelivery, text: string, };
