// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterAgentDeliveryReceipt } from "./InterAgentDeliveryReceipt";

export type InterAgentDeliveryStatus = { "state": "unknown", messageId: string, semanticSha256: string, } | { "state": "pending", messageId: string, semanticSha256: string, } | { "state": "context_persisted", messageId: string, semanticSha256: string, receipt: InterAgentDeliveryReceipt, } | { "state": "conflict", messageId: string, semanticSha256: string, } | { "state": "retryable_error", messageId: string, semanticSha256: string, };
