// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentManagementPhase } from "./AgentManagementPhase";
import type { AgentManagementReplacePolicy } from "./AgentManagementReplacePolicy";
import type { AgentManagementRotationMode } from "./AgentManagementRotationMode";
import type { CutexParticipantPresentation } from "./CutexParticipantPresentation";
import type { ManagedAgentActivityStatus } from "./ManagedAgentActivityStatus";
import type { ManagedAgentOperation } from "./ManagedAgentOperation";

/**
 * UI-only lifecycle for a durable Cutex-managed agent.
 *
 * These identifiers deliberately remain opaque strings. They are not native Codex `ThreadId`s
 * or `AgentPath`s and must never be used to establish native sub-agent ownership.
 */
export type ManagedAgentActivityItem = {
/**
 * Stable action identity used to update one visible activity.
 */
id: string,
/**
 * Unique source-event identity used for idempotent ingestion.
 */
eventId: string,
/**
 * Monotonic sequence for this action.
 */
sequence: bigint,
/**
 * Source event time, in Unix milliseconds.
 */
occurredAtMs: bigint,
/**
 * Authoritative Cutex project identity for frontend-local presentation correlation.
 */
projectId?: string, operation: ManagedAgentOperation, status: ManagedAgentActivityStatus, actionId?: string, phaseEventId?: string, phase?: AgentManagementPhase, managedAgentId: string, managedAgentName: string | null, managedAgentMetadata?: CutexParticipantPresentation, predecessorAgentId?: string, predecessorAgentName?: string, predecessorMetadata?: CutexParticipantPresentation, successorAgentId?: string, successorAgentName?: string, successorMetadata?: CutexParticipantPresentation, replacePolicy?: AgentManagementReplacePolicy, rotationMode?: AgentManagementRotationMode, authorityEpoch?: bigint, managedAgentRole: string | null, initialTaskPreview: string | null, detail: string | null, runtimeGeneration: bigint | null, };
