// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterAgentDeliveryMode } from "../InterAgentDeliveryMode";
import type { CutexParticipantPresentation } from "./CutexParticipantPresentation";
import type { OutboundInterAgentMessageStatus } from "./OutboundInterAgentMessageStatus";

/**
 * UI-only record of a message sent through the Cutex Agent Bus.
 */
export type OutboundInterAgentMessageItem = {
/**
 * Stable message identity used to update one visible activity.
 */
id: string,
/**
 * Unique source-event identity used for idempotent ingestion.
 */
eventId: string,
/**
 * Monotonic sequence for this message.
 */
sequence: bigint,
/**
 * Source event time, in Unix milliseconds.
 */
occurredAtMs: bigint, senderAgentId: string, senderAgentName: string | null, senderMetadata?: CutexParticipantPresentation, recipientAgentId: string, recipientAgentName: string | null, recipientMetadata?: CutexParticipantPresentation, otherRecipientAgentIds: Array<string>, deliveryMode: InterAgentDeliveryMode, status: OutboundInterAgentMessageStatus,
/**
 * Bounded display-only preview. The full function-call argument remains the model-visible
 * source of truth and is never reconstructed from this field.
 */
contentPreview: string | null, detail: string | null, };
