// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresentationAppended } from "./PresentationAppended";

export type PresentationAppendedNotification = { threadId: string, position: number, item: PresentationAppended, };
