// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Presentation } from "./Presentation";

export type PresentationAppended = { version: number, ownerId: string, originThreadId: string, presentation: Presentation, semanticSha256: string, receiptId: string, };
