// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalInputSource } from "./ExternalInputSource";
import type { PresentationFormat } from "./PresentationFormat";
import type { PresentationReference } from "./PresentationReference";

export type Presentation = { id: string, source: ExternalInputSource, title: string, body: string, format: PresentationFormat, references: Array<PresentationReference>, };
