// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskAssignmentActivityStatus = "committed" | "communicationRecorded" | "attemptStarted" | "attemptAcknowledged" | "attemptProgressed" | "attemptBlocked" | "attemptResumed" | "retryScheduled" | "reviewReady" | "completed" | "failed" | "closed" | "declined" | "aborted";
