// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CutexParticipantPresentation } from "./CutexParticipantPresentation";
import type { TaskWatchdogActivityKind } from "./TaskWatchdogActivityKind";
import type { TaskWatchdogStage } from "./TaskWatchdogStage";

/**
 * Raw presentation-only metadata for one stale-running Task Service episode.
 */
export type TaskWatchdogActivityItem = {
/**
 * Stable episode identity shared by every stage of one stale interval.
 */
id: string, eventId: string, eventKey: string, sequence: bigint, occurredAtMs: bigint, projectId?: string, taskId: string, taskRevision: bigint, assignmentId: string, attemptNumber: bigint, directorAgentId: string, assigneeAgentId: string, assigneeMetadata?: CutexParticipantPresentation, activityWatermark: string, activityKind: TaskWatchdogActivityKind, idleDurationSecs: bigint, stage: TaskWatchdogStage, sourceSequence: bigint, };
