// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskServiceMessageClass } from "./TaskServiceMessageClass";

/**
 * Bounded semantic fields already authenticated at Task Service ingress. Mechanical provider
 * identifiers are deliberately absent, and this value is never serialized into rollout state.
 */
export type TaskServiceMessagePresentation = { class: TaskServiceMessageClass, taskName: string, assignmentId: string, projectId?: string, transition?: string, semanticPayload: string, };
