// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CutexParticipantPresentation } from "./CutexParticipantPresentation";
import type { TaskAssignmentActivityStatus } from "./TaskAssignmentActivityStatus";

/**
 * Typed UI reducer input for Cutex Task Service assignment and attempt transitions.
 *
 * A future task panel must still requery the authoritative Task Service snapshot; these watch
 * events are durable timeline records and sequence-bearing invalidation hints, not authority.
 */
export type TaskAssignmentActivityItem = {
/**
 * Stable assignment identity used to update one visible activity.
 */
id: string,
/**
 * Unique source-event identity used for idempotent ingestion.
 */
eventId: string,
/**
 * Monotonic Task Service sequence for the assignment.
 */
sequence: bigint,
/**
 * Source event time, in Unix milliseconds.
 */
occurredAtMs: bigint, taskId: string, taskTitle: string | null, directorAgentId: string, directorAgentName: string | null, directorMetadata?: CutexParticipantPresentation, assigneeAgentId: string, assigneeAgentName: string | null, assigneeMetadata?: CutexParticipantPresentation, status: TaskAssignmentActivityStatus, attemptId: string | null, attemptNumber: number | null, detail: string | null, };
