// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadInterAgentMessageParams = { threadId: string, author: string, recipient: string, otherRecipients: Array<string>, content: string, triggerTurn: boolean, };
