// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CutexUiActivity } from "./CutexUiActivity";
import type { CutexUiActivityDelivery } from "./CutexUiActivityDelivery";

/**
 * Strictly UI-only Cutex activity ingestion. This method cannot append response items or start a
 * turn and is rejected for native parent-owned sub-agent threads.
 */
export type ThreadCutexActivityParams = { threadId: string, delivery: CutexUiActivityDelivery, activity: CutexUiActivity, };
