// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterAgentDeliveryStatus } from "./InterAgentDeliveryStatus";

export type ThreadInterAgentMessageStatusResponse = { schema: string, threadId: string, statuses: Array<InterAgentDeliveryStatus>, };
