// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterAgentDeliveryMode } from "../InterAgentDeliveryMode";
import type { CutexParticipantPresentation } from "./CutexParticipantPresentation";

export type ThreadInterAgentMessageParams = { threadId: string, messageId: string, author: string, recipient: string, otherRecipients?: Array<string> | null, content: string, deliveryMode: InterAgentDeliveryMode, authorMetadata?: CutexParticipantPresentation, recipientMetadata?: CutexParticipantPresentation, };
