// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Historical label only; in particular `interrupt` never interrupts a resumed thread.
 */
export type LegacyInterAgentDeliveryMode = "after_turn" | "soon" | "passive" | "interrupt";
