// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { LegacyInterAgentDeliveryMode } from "./LegacyInterAgentDeliveryMode";

export type LegacyInterAgentMessageItem = { id: string, author: AgentPath, recipient: AgentPath, otherRecipients: Array<AgentPath>, content: string, deliveryMode: LegacyInterAgentDeliveryMode, };
